---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Install Python3-apt"
  package:
    name: "{{ package }}"
  register: package_status
  until: package_status is succeeded
  retries: 3
